name: nbconvert-service
channels:
  - defaults
dependencies:
  - attrs=19.3.0
  - backcall=0.1.0
  - bleach=3.1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - click=7.1.1
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - flask=1.1.1
  - importlib_metadata=1.5.0
  - ipython_genutils=0.2.0
  - itsdangerous=1.1.0
  - jedi=0.16.0
  - jinja2=2.11.1
  - jsonschema=3.2.0
  - jupyter_core=4.6.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nbformat=5.0.4
  - ncurses=6.2
  - openssl=1.1.1e
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.6.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - prompt_toolkit=3.0.3
  - pygments=2.6.1
  - pyrsistent=0.15.7
  - python=3.8.1
  - readline=7.0
  - setuptools=46.0.0
  - sqlite=3.31.1
  - testpath=0.4.4
  - tk=8.6.8
  - traitlets=4.3.3
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - werkzeug=1.0.0
  - wheel=0.34.2
  - xz=5.2.4
  - zipp=2.2.0
  - zlib=1.2.11
  - pip:
    - appnope==0.1.0
    - cachetools==4.0.0
    - chardet==3.0.4
    - google-auth==1.4.2
    - idna==2.8
    - ipykernel==4.6.1
    - ipython==5.5.0
    - jupyter-client==6.1.0
    - nbconvert==5.2.1
    - notebook==5.2.2
    - numpy==1.18.2
    - pandas==0.24.2
    - portpicker==1.2.0
    - prompt-toolkit==1.0.18
    - ptyprocess==0.6.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - python-dateutil==2.8.1
    - pytz==2019.3
    - pyzmq==19.0.0
    - requests==2.21.0
    - rsa==4.0
    - simplegeneric==0.8.1
    - six==1.12.0
    - terminado==0.8.3
    - tornado==4.5.3
    - urllib3==1.24.3

